// 权限键单一来源（与后端 model.ModuleActions 对齐）：
// 动作 read=查看 / write=编辑(增删改) / calculate=核算 / export=导出。
// 路由 meta 与 v-permission 按钮围栏共用，新增模块/动作同步后端定义。
export const PERM = {
  homeRead: 'home.read',
  personRead: 'person.read',
  personWrite: 'person.write',
  personExport: 'person.export',
  companyRead: 'company.read',
  companyWrite: 'company.write',
  companyExport: 'company.export',
  positionEventRead: 'position_event.read',
  positionEventWrite: 'position_event.write',
  positionEventExport: 'position_event.export',
  attendanceRead: 'attendance.read',
  attendanceWrite: 'attendance.write',
  attendanceCalculate: 'attendance.calculate',
  attendanceExport: 'attendance.export',
  annualLeaveRead: 'annual_leave.read',
  annualLeaveWrite: 'annual_leave.write',
  annualLeaveCalculate: 'annual_leave.calculate',
  annualLeaveExport: 'annual_leave.export',
  salaryRead: 'salary.read',
  salaryWrite: 'salary.write',
  salaryCalculate: 'salary.calculate',
  salaryExport: 'salary.export',
  fileRead: 'file.read',
  fileWrite: 'file.write',
  fileExport: 'file.export',
  auditRead: 'audit.read',
  auditExport: 'audit.export',
  userRead: 'user.read',
  userWrite: 'user.write',
  roleRead: 'role.read',
  roleWrite: 'role.write',
  systemConfigRead: 'system_config.read',
  systemConfigWrite: 'system_config.write',
} as const
