// 权限键单一来源（与后端 model.ModuleActions 对齐，按菜单叶子模块划分）：
// 动作 read=查看 / write=编辑(增删改) / calculate=核算 / export=导出。
// 路由 meta 与 v-permission 按钮围栏共用，新增模块/动作同步后端定义。
export const PERM = {
  personRead: 'person.read',
  personWrite: 'person.write',
  personExport: 'person.export',
  companyRead: 'company.read',
  companyWrite: 'company.write',
  companyExport: 'company.export',
  positionEventRead: 'position_event.read',
  positionEventWrite: 'position_event.write',
  positionEventExport: 'position_event.export',
  attendanceEventRead: 'attendance_event.read',
  attendanceEventWrite: 'attendance_event.write',
  attendanceEventExport: 'attendance_event.export',
  attendanceDailyRead: 'attendance_daily.read',
  attendanceDailyExport: 'attendance_daily.export',
  attendanceMonthlyRead: 'attendance_monthly.read',
  attendanceMonthlyCalculate: 'attendance_monthly.calculate',
  attendanceMonthlyExport: 'attendance_monthly.export',
  annualLeaveEventRead: 'annual_leave_event.read',
  annualLeaveEventWrite: 'annual_leave_event.write',
  annualLeaveEventExport: 'annual_leave_event.export',
  leaveInLieuRead: 'leave_in_lieu.read',
  annualLeaveCarryoverRead: 'annual_leave_carryover.read',
  annualLeaveCarryoverCalculate: 'annual_leave_carryover.calculate',
  salaryEventRead: 'salary_event.read',
  salaryEventWrite: 'salary_event.write',
  salaryEventExport: 'salary_event.export',
  salarySummaryRead: 'salary_summary.read',
  salarySummaryCalculate: 'salary_summary.calculate',
  salarySummaryExport: 'salary_summary.export',
  userRead: 'user.read',
  userWrite: 'user.write',
  roleRead: 'role.read',
  roleWrite: 'role.write',
  systemConfigRead: 'system_config.read',
  systemConfigWrite: 'system_config.write',
  fileRead: 'file.read',
  fileWrite: 'file.write',
  auditRead: 'audit.read',
  auditExport: 'audit.export',
} as const
